In [1]:
import numpy as np

#numpy array

In [6]:
benimListem=[20,30,40]

In [8]:
type(benimListem)

list

In [12]:
np.array(benimListem)

array([20, 30, 40])

In [14]:
matrixListesi=[[10,2,3],[2,3,4]]

In [16]:
matrixListesi[1][0]

2

In [18]:
np.array(matrixListesi)

array([[10,  2,  3],
       [ 2,  3,  4]])

arange

In [21]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
 np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#zeros

In [33]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [37]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

##linspace

In [48]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

eye

In [55]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

RANDOM

In [60]:
np.random.randn(4)

array([-0.86667987, -0.10435161,  0.15670332,  0.36845287])

In [62]:
np.random.randn(4,4)

array([[ 1.34764579, -0.92828853, -0.83928023, -1.8237353 ],
       [ 2.96110039,  0.28593702,  1.06117126,  1.57082737],
       [ 1.32696127, -0.4089317 , -2.21803619,  0.19402043],
       [ 0.81817792,  0.17533591,  0.82553469, -0.07416125]])

In [64]:
np.random.randint(1,10)

5

In [66]:
np.random.randint(1,10,5)

array([2, 6, 6, 7, 1])

In [68]:
benimNumpyDizim=np.arange(30)

In [70]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [72]:
benimRandomDizim=np.random.randint(0,100,30)
benimRandomDizim

array([66, 17, 56, 83, 55, 35, 97,  2, 10, 93, 55, 27, 43, 95,  3, 33, 28,
       45, 35,  4, 53, 63, 87, 35, 86, 44, 74, 52, 58, 53])

NUMPY DİZİ METHODLARI

In [77]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [79]:
benimNumpyDizim.max()

29

In [81]:
benimRandomDizim.max()

97

In [83]:
benimRandomDizim.argmax()

6

In [85]:
benimRandomDizim.argmin()

7

In [89]:
reshapeDizim=benimNumpyDizim.reshape(5,6)

In [93]:
reshapeDizim.shape

(5, 6)

In [99]:
benimDizim=np.arange(0,15)

In [101]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [103]:
benimDizim[5]

5

In [107]:
benimDizim[3:5]

array([3, 4])

In [109]:
benimDizim[3:8]=-5

In [111]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [113]:
baskaDizi=np.arange(0,24)

In [138]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [140]:
slicingDizisi=baskaDizi[4:9]

In [142]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [143]:
slicingDizisi[:]=700

In [147]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [149]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [151]:
ornekDizi=np.arange(0,24)

In [153]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [155]:
ornekDiziKopyasi=ornekDizi.copy()

In [157]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [159]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [161]:
ornekDiziKopyasiSlicing=ornekDiziKopyasi[3:6]

In [165]:
ornekDiziKopyasiSlicing[:]=800

In [167]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [169]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

MATRİX

In [178]:
benimListem=[[10,20,30],[4,5,6]]

In [180]:
benimMatrixDizim=np.array(benimListem)

In [182]:
benimMatrixDizim

array([[10, 20, 30],
       [ 4,  5,  6]])

In [184]:
benimMatrixDizim[0]

array([10, 20, 30])

In [186]:
benimMatrixDizim[1][2]

6

In [188]:
benimMatrixDizim[1,2]

6

In [198]:
benimMatrixDizim[1:,1:]

array([[5, 6]])

In [204]:
yeniListe=[[0,1,2,3],[3,4,5]]

In [210]:
yeniMatrix =np.array(yeniListe)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [1]:
#OPERASYONLAR

In [5]:
import numpy as np
yenibirdizi=np.random.randint(1,100,20)

In [6]:
yenibirdizi

array([10, 82,  2, 23, 80, 43, 64, 73, 51, 59, 18,  8, 94, 77, 52, 84, 82,
       55, 79, 58])

In [8]:
sonucdizi=yenibirdizi>24

In [9]:
sonucdizi

array([False,  True, False, False,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [10]:
yenibirdizi[sonucdizi]

array([82, 80, 43, 64, 73, 51, 59, 94, 77, 52, 84, 82, 55, 79, 58])

In [11]:
yenibirdizi[yenibirdizi>24]

array([82, 80, 43, 64, 73, 51, 59, 94, 77, 52, 84, 82, 55, 79, 58])

In [12]:
sondizi=np.arange(0,24)

In [13]:
sondizi=np.arange(0,24)

In [14]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
sondizi+sondizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [16]:
sondizi*sondizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [17]:
sondizi-sondizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [18]:
np.sqrt(sondizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])